### ISSUE TITLE
relative_thermal_limit

### ISSUE THREAD

**Issue by bdonon** [MarvinLer/pypownet#1]
Change this variable name to something like "line_capacity_usage"

**Comment by bdonon** [comment]
Also, we should have access to both the actual flow in the lines, and the thermal limit, and not just a normalized version of the flows

**Comment by MarvinLer** [comment]
Changed "relative_thermal_limits" into "lines_capacity_usage" for the class Observation in 6103d8d.
Can you make a standalone feature request for the splitting of the capacity usage vector please ?

**Comment by bdonon** [comment]
ok!

**Comment by MarvinLer** [comment]
thanks!
