### ISSUE TITLE
Flows and thermal limits

### ISSUE THREAD

**Issue by bdonon** [MarvinLer/pypownet#10]
we should have access to both the actual flow in the lines, and the thermal limit, and not just a normalized version of the flows

**Comment by MarvinLer** [comment]
Added the list of thermal limits (fixed through time) in c0c7922.
Changed the 'lines_capacity_usage' attribute of class Observation into 'ampere_flows' in 46d32c0: the list of size the number of lines now contain the Ampere value of the flow (identical at both origin and extremity).
