### ISSUE TITLE
Action understandability

### ISSUE THREAD

**Issue by bdonon** [MarvinLer/pypownet#11]
We would need to be able to identify, the elements in the action vector that correspond to each substation. The current implementation already offers an easier to understand action ordering, but the problem is that you don't know where the limit between each node is.
If I were to try every possible topological combination for a specific node, it's quite hard to identify which parts of the action vector could be modified

**Comment by MarvinLer** [comment]
Various work has been done regarding both action and observation understandability. There are now various helpers and classes which can reduce the observation space. Consult the new documentation for further information: https://pypownet.readthedocs.io/en/latest/env_info.html
