### ISSUE TITLE
Reward

### ISSUE THREAD

**Issue by bdonon** [MarvinLer/PyPowNet#14]
The reward is not fully finished.
It doesn't take into account a load cut

**Comment by MarvinLer** [comment]
Fixed cost of actions subreward in c262e09: the get_reward function of RunEnv now takes the input action (last one played) into account.

**Comment by MarvinLer** [comment]
Added cut loads within the reward computation in 86086c3. Also added number of cut loads within an observation for quick feature integration (will need some refacto/scaling).
Also, we could have a threshold on the maximum % of cut loads tolerated before game over.

**Comment by MarvinLer** [comment]
Closing: will add more features to reward but it is 100% operational in its current state.
