### ISSUE TITLE
Time lag for line breaking

### ISSUE THREAD

**Issue by bdonon** [MarvinLer/pypownet#15]
This is a "long-term" feature request

Isabelle suggests that if there is an overflow, we wait a few time steps before opening the line. This time lag is still to be defined. However, the impact on the cascading failure, would be that it would prevent it from being instantaneous.

**Comment by MarvinLer** [comment]
Added in f5012a689ea098eac778b36adfab2a865dd325f4.
Now, there is a time lag parametrable for continuous soft-overflowed lines: if a line is overflowed but not hard-overflowed for several timesteps, it will break at the time limit for a fixed number of timesteps.
