### ISSUE TITLE
Pausing / unpausing the renderer

### ISSUE THREAD

**Issue by BDonnot** [MarvinLer/PyPowNet#17]
This repository's issues are reserved for feature requests and bug reports.

* **You are submitting a ...**
  - [ ] bug report
  - [x ] feature request

* **What is the current behavior?**
You can't pause the renderer

* **If the current behavior is a bug, please provide the steps to reproduce**

* **What is the expected behavior?**
Key press when the rederer is active would atomatically pause it at the current frame. Another key pressed, and the work would resume where it has been paused.

* **Please tell us about your environment:**

  - Version: 2.0.3
  - OS: Linux (ubuntu 16.04)
  - Installation source: setup.py

* **Other information** (e.g. detailed explanation, stack/error traces, related issues, suggestions how to fix)

**Comment by MarvinLer** [comment]
Added in fed2e99.
Thanks for your contribution! Enhance it a bit: pause/unpause the game by pressing space bar, exit by either clicking the cross on top-right or by pressing ESCAPE. Will probably add more such interactive features in the future.
