### ISSUE TITLE
CSV files missing for 118 case

### ISSUE THREAD

**Issue by amar-iastate** [MarvinLer/pypownet#20]
Hi Marvin,
Thanks for making this repository public.
The files 'hazards.csv' and 'maintenance.csv' are missing in the input folder for 118 bus. Can you please upload them?
Also is there any documentation on how to create the .csv files for larger cases?
Thanks
Amar

**Comment by MarvinLer** [comment]
Hello,

Added the hazards and maintenance CSV files for case118 in a0bd724de5becd0f0daeec2e0cc5582cf3106960. We plan to refactor the way the input of the software are dealt with, and this include some documentation about the chronics (.csv files) as well as some scripts to generate adequate reference grids of larger cases (from standard IEEE files). Unfortunately I doubt we will be able to open-source script for generating CSV files relative to the injections (productions P and V and consumptions P and Q). I can however send you a snippet of code if you want to generate maintenance and hazards CSV files for the cases already integrated within the software (cases 14, 30 and 118 atm).

**Comment by amar-iastate** [comment]
Thanks Marvin!

Can you please send me the code to generate the maintenance and hazards CSV files for the existing cases. 
Also, I was looking at the ipython notebooks and there was a link to your masters thesis on github. I dont think it is available in the provided link. Is it possible for you to upload your thesis so that it is clear what exactly the agent is trying to control?

Cheers
Amar

**Comment by MarvinLer** [comment]
Added project presentation PDF (master thesis) in 9fb71a593e85eadd2435384cf8454db6d3968248 (in doc/ folder). The document is a bit outdated, but apart from some modelization modifications, the overall content remains accurate.
Also, the documentation to come will go into more details about the behavior of the software.

Best
Marvin

**Comment by MarvinLer** [comment]
Here is a gist to generate new hazards and maintenance files based on pre-existing ones (the ones inside the input/chronics/%d folders).

**Comment by amar-iastate** [comment]
Thanks Marvin!

**Comment by MarvinLer** [comment]
Hi Amar,

The user manual is available at https://pypownet.readthedocs.io/en/latest/.

Best,
Marvin

**Comment by amar-iastate** [comment]
Thank you Marvin
Very nice work !!


Thanks and Regards
Amar
