### ISSUE TITLE
Test clean Install de PyPownet - Bugs

### ISSUE THREAD

**Issue by marota** [MarvinLer/pypownet#23]
**Describe the bug**
Installation avec Docker de PyPownet sur Mac.
Insatll complete.
Bugs:
- en lançant python -m **pypownet.main => ModuleNotFoundError:** No module named 'oct2py'
- en lançant sudo docker run -it --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" marvinler/pypownet sh 
=> Unable to find image 'marvinler/pypownet:latest' locally
docker: Error response from daemon: manifest for marvinler/pypownet:latest not found.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MarvinLer** [comment]
I changed the version in README for the current version of the docker tag.
The message "=> Unable to find image 'marvinler/pypownet:latest' locally" indicates that the image is not found, did you pull the docker image ? sudo docker pull marvinler/pypownet:2.1.1

Also, if you install this package using Docker, you effectively need to run the command:
sudo docker run -it --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" marvinler/pypownet:2.1.1 sh
It will open a terminal within the image, directly at the top directory of pypownet. Within the terminal, you can use the software as indicating in basic usage e.g. python -m pypownet.main

**Comment by MarvinLer** [comment]
Is it OK now ?

**Comment by marota** [comment]
Yes the docker version was outdated (pypownet:2.1.1 instead of pypownet:latest)

I managed to run it on Fedora 25, but I needed to add --privileged option to run the X server from docker:
sudo docker run -it  --privileged --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" marvinler/pypownet:2.1.1 sh

**Comment by MarvinLer** [comment]
OK thanks for the feedback, I will add the ``--privileged`` flag to the installation process.
