### ISSUE TITLE
Change the renderer legend

### ISSUE THREAD

**Issue by marota** [MarvinLer/pypownet#24]
**Describe the bug**
llustration of the renderer with the default14/ environment; note that the renderer drastically slows the performance of pypownet: it takes ~40s to compute 1000 timesteps without renderer mode.

**Change**
llustration of a running power grid with our renderer on the default IEEE14 grid environment.
NB: the renderer drastically slows the performance of pypownet. it takes ~40s to compute 1000 timesteps without renderer mode.

**Comment by MarvinLer** [comment]
done
