### ISSUE TITLE
Action.__getitem__() returns nothing

### ISSUE THREAD

**Issue by luvf** [MarvinLer/pypownet#25]
correction :
ai placé de return
aussi une petite modification de setatrr pour plus de clareté.

class Action(object):
    def __init__(self, prods_switches_subaction, loads_switches_subaction,
                 lines_or_switches_subaction, lines_ex_switches_subaction, lines_status_subaction):
        if prods_switches_subaction is None:
            raise ValueError('Expected prods_switches_subaction to be array, got None')
        if loads_switches_subaction is None:
            raise ValueError('Expected loads_switches_subaction to be array, got None')
        if lines_or_switches_subaction is None:
            raise ValueError('Expected lines_or_switches_subaction to be array, got None')
        if lines_ex_switches_subaction is None:
            raise ValueError('Expected lines_ex_switches_subaction to be array, got None')
        if lines_status_subaction is None:
            raise ValueError('Expected lines_status_subaction to be array, got None')

        self.prods_switches_subaction = np.asarray(prods_switches_subaction).astype(int)
        self.loads_switches_subaction = np.asarray(loads_switches_subaction).astype(int)
        self.lines_or_switches_subaction = np.asarray(lines_or_switches_subaction).astype(int)
        self.lines_ex_switches_subaction = np.asarray(lines_ex_switches_subaction).astype(int)
        self.lines_status_subaction = np.asarray(lines_status_subaction).astype(int)

        self._prods_switches_length = len(self.prods_switches_subaction)
        self._loads_switches_length = len(self.loads_switches_subaction)
        self._lines_or_switches_length = len(self.lines_or_switches_subaction)
        self._lines_ex_switches_length = len(self.lines_ex_switches_subaction)
        self._lines_status_length = len(self.lines_status_subaction)

    def get_prods_switches_subaction(self):
        return self.prods_switches_subaction

    def get_loads_switches_subaction(self):
        return self.loads_switches_subaction

    def get_lines_or_switches_subaction(self):
        return self.lines_or_switches_subaction

    def get_lines_ex_switches_subaction(self):
        return self.lines_ex_switches_subaction

    def get_node_splitting_subaction(self):
        return np.concatenate((self.get_prods_switches_subaction(), self.get_loads_switches_subaction(),
                               self.get_lines_or_switches_subaction(), self.get_lines_ex_switches_subaction(),))

    def get_lines_status_subaction(self):
        return self.lines_status_subaction

    def as_array(self):
        return np.concatenate((self.get_node_splitting_subaction(), self.get_lines_status_subaction(),))

    def __str__(self):
        return ', '.join(list(map(str, self.as_array())))

    def __len__(self, do_sum=True):
        length_aslist = (self._prods_switches_length, self._loads_switches_length, self._lines_or_switches_length,
                         self._lines_ex_switches_length, self._lines_status_length)
        return sum(length_aslist) if do_sum else length_aslist

    def __setitem__(self, item, value):
        item %= len(self)
        if item < self._prods_switches_length:
            self.prods_switches_subaction.__setitem__(item, value)
            return
        item -= self._prods_switches_length
        
        if item < self._loads_switches_length:
            self.loads_switches_subaction.__setitem__(item, value)
            return
        item -= self._loads_switches_length

        if item < self._lines_or_switches_length:
            self.lines_or_switches_subaction.__setitem__(item, value)
            return
        item -= self._lines_or_switches_length

        if item < self._lines_ex_switches_length:
            self.lines_ex_switches_subaction.__setitem__(item, value)
            return
        item -= self._lines_ex_switches_length

        self.lines_status_subaction.__setitem__(item, value)

    def __getitem__(self, item):
        item %= len(self)
        
        if item < self._prods_switches_length:
            return self.prods_switches_subaction.__getitem__(item)
        item -= self._prods_switches_length

        if item < self._loads_switches_length:
            return self.loads_switches_subaction.__getitem__(item)
        item -= self._loads_switches_length

        if item < self._lines_or_switches_length:
            return self.lines_or_switches_subaction.__getitem__(item)
        item -= self._lines_or_switches_length

        if item < self._lines_ex_switches_length:
            return self.lines_ex_switches_subaction.__getitem__(item)
        item -= self._lines_ex_switches_length
        
        return self.lines_status_subaction.__getitem__(item)

**Comment by MarvinLer** [comment]
Corrected in 6a196b546156b36434c35a4ef8004694ea15cf1c, thanks!
