### ISSUE TITLE
Codalab pytorch

### ISSUE THREAD

**Issue by bdonon** [MarvinLer/pypownet#29]
When submitting an controller on the Codalab page of the challenge, I encountered the following error : ModuleNotFoundError: No module named 'torch'
torch should be available

**Comment by MarvinLer** [comment]
I guess this would be more appropriate on the repo for Codalab :)

**Comment by MarvinLer** [comment]
https://github.com/MarvinLer/l2rpn_bundle_codalab/issues/2
