### ISSUE TITLE
Confusing action name

### ISSUE THREAD

**Issue by bdonon** [MarvinLer/pypownet#30]
In agent.py, in the GreedySearch agent, we observed the following line of code:

action_space.set_switches_configuration_of_substation(action=action,
                                                                          substation_id=substation_id,
                                                                          new_configuration=new_configuration)

It mentions a 'new_configuration' as the action. However, it is confusing with regards to the action space encoding that we have designed and used so far. Here the term 'new_configuration' can make people think that this is the topology state that we want our grid to be, while it is actually just a vector that says which connections you want to modify.

**Comment by MarvinLer** [comment]
Yes the name is misleading. Changes in 9491c2c1f404a5842296e733e0df17d028413cf1:

- in class ActionSpace: renamed get_switches_configuration_of_substation -> get_substation_switches and set_switches_configuration_of_substation -> set_substation_switches; also renamed parameter new_configuration -> new_values
- both these functions can now handle actions of array type (eg numpy arrays)

Is it more clear ?

**Comment by MarvinLer** [comment]
Changed in 2ca7c2b2c662a0f593500f809c4788ae88ecfbce + 87dabe89b464dad4323c1c1ee8fca0824f3aec47 the names by adding '_in_action' such that this is more clear that it deals with actions and not observations. Please consult the docstring for more info (doc not updated regarding this). Also added the same functions but that work directly on Action objects: given an `Action`, you can call `action.get_substation_switches_in_action(1)` to get eg the current values within the action of the switches of the substation 1; this could be used to interpret in terms of grid conduct the actions played by a RL model. The behaviors for these two new functions working on actions is the same as the ones in action_space. _Note: call `self.environment.action_space.array_to_action(action)` on a array-type action such as np array to convert it into a proper `Action`._
