### ISSUE TITLE
DoNothing incompatibility with new Observation and Action

### ISSUE THREAD

**Issue by bdonon** [MarvinLer/pypownet#32]
There are some bugs when running the do-nothing action defined in agent.py, since observations and actions are now numpy arrays.

**Comment by MarvinLer** [comment]
Added explicit DoNothing agent in ae87d20ad5537639139a7a4a7fb435283c39e6c0 (use `-a DoNothing` in cli) and changed Agent class into an abstract class (not sure whether you were referring to this agent class).
Please re-open ticket with details if not pertinent changes to your issue.
