### ISSUE TITLE
L'agent par défaut n'est pas défini

### ISSUE THREAD

**Issue by vincentbarbesant** [MarvinLer/pypownet#34]
Après avoir suivi la procédure d'installation (sans docker) telle que décrite dans le README.md, je lance la commande `python -m pypownet.main` suggérée dans la section Basic Usage.

Je tombe sur l'erreur suivante :
`File "/home/barbesantvin/challenge/pypownet/pypownet/main.py", line 52, in main agent = agent_class(env)`
`TypeError: Can't instantiate abstract class Agent with abstract methods act`

Cela est du au fait que l'agent par défaut défini dans le `main.py` est `Agent`  au lieu de `DoNothing` :
`parser.add_argument('-a', '--agent', metavar='AGENT_CLASS', default='Agent', type=str, help='class to use for the agent (must be within the \'pypownet/agent.py\' file); 'default class Agent') `

A titre de vérification, quand je lance la commande `python -m pypownet.main --agent DoNothing`, tout se passe bien.

**Comment by MarvinLer** [comment]
Fixed in 976524ff428e7240eb7daf1f9f35e2989e98b8f2: the class Agent was shortly passed into an abstract class which raises the above bug.
ML
