### ISSUE TITLE
Install: no module named gym

### ISSUE THREAD

**Issue by marota** [MarvinLer/pypownet#36]
**Describe the bug**
Dependency with 'gym' but not listed in read-me. Problem when running pypownet.main the first time.

=> update read.me for git install (and maybe docker)

**Comment by MarvinLer** [comment]
Did you run `python3.6 setup.py install` (step 5 of current README) ? The
gym dependency is listed inside the requirements.txt file which contains
the libraries installed when running the setup

**Comment by marota** [comment]
Ok I didn't rerun setup.py with requirements.txt and gym is among requirements
