### ISSUE TITLE
Fix amperes values

### ISSUE THREAD

**Issue by camiloromers** [MarvinLer/pypownet#37]
Amperes values in observation are not computed correctly. There's a mismatch with values computed with theory. The difference is affected by a factor of 10.

**Comment by MarvinLer** [comment]
The formula used in the software is: ampere flows = sqrt(p*p +
q*q)/(sqrt(3) * v)
where p is active value, q reactive value and v voltage value (there is
also a clipping of these values beforehand for potential diverged values)
Is this formula correct ? or is a factor missing (something about mva) ?

**Comment by camiloromers** [comment]
Ok but if you take v from the environment you have to multiplied by 100 kV
because the values are on per unit and you have to convert them into KV.

**Comment by MarvinLer** [comment]
This would yield a factor of 100 != 10 no ?

**Comment by camiloromers** [comment]
I think so, but which voltage you are using to compute the current? from where?

**Comment by MarvinLer** [comment]
Fixed in 5bf69f2aa1f73f22efc51101251dbfb6c59d22f2, thanks for the help!
