### ISSUE TITLE
Max number action bug

### ISSUE THREAD

**Issue by marota** [MarvinLer/pypownet#41]
in game.py, in _verify_illegal_action: 
'if n_switched_substations > self.max_number_actionned_lines \'

should be
if n_switched_substations > self.max_number_actionned_substations

**Comment by MarvinLer** [comment]
Good catch, will be fixed tonight

**Comment by MarvinLer** [comment]
Fixed in b1274a54bb226c8c6e3cf0fc68f12a853e8715eb.
