### ISSUE TITLE
apply_topology in game.py - load setting problem

### ISSUE THREAD

**Issue by marota** [MarvinLer/pypownet#42]
From these lines:
!# Replace their values with the one of its associated node
  bus[id_bus, 2] = bus[(lo + self.n_nodes // 2) % self.n_nodes, 2]
bus[id_bus, 3] = bus[(lo + self.n_nodes // 2) % self.n_nodes, 3]

you should replace "lo" by id_bus:
=> bus[id_bus, 2] = bus[(id_bus + self.n_nodes // 2) % self.n_nodes, 2]

and maybe do more simply:
bus[id_bus, 2] = bus[id_bus + self.n_nodes // 2 , 2]

**Comment by MarvinLer** [comment]
indeed!

**Comment by MarvinLer** [comment]
Fixed in 2794fec3f2bcf3c68f2a5ec33460c11029efbb55
