### ISSUE TITLE
simulate interference

### ISSUE THREAD

**Issue by marota** [MarvinLer/pypownet#43]
Simulate method is still modifying the environment.

**Test:**
To see that, you can run a simple do nothing agent vs a do nothing agent after simulating at least 2 actions. If the rewards timestep after timestep are not the same, it means that simulation is interferring.

**Bugs:**
1) Using resetting load_entries_from_timestep_id in reload_minus_1_timestep  :
=> it resets the production values to the values of the chronic after a simulation, which were not the values of the production before the simulation. Indeed before a simulation, the state of the grid is a result of a load flow after applying the chronics and a previous action. The load-flow adjust the productions from the chronics, especially for the slack bus. So reapplying the chronics without a load-flow does not give the same state.
2) self.grid.mpc = copy.deepcopy(before_mpc) + apply_topo in reload_minus_1_timestep:
=> if you resset the mpc, it should not be modified because of apply_topo then. However you should also reset "are_loads" which is modified in apply_topo but was not reset

**Before in reload_minus_1_timestep:**
            self.grid.mpc = before_mpc  # Change grid mpc before apply topo
            self.grid.apply_topology(before_topology)  # Change topo before loading entries (reflects what happened)
            self.load_entries_from_timestep_id(before_timestep_id, silence=True)

**Should be changed for:**
            self.grid.mpc = before_mpc  # Change grid mpc before apply topo
            self.grid.are_loads=before_are_loads
            self.current_timestep_id=before_timestep_id 

Don't forget to copy are_loads when starting simulate:
before_are_loads=copy.deepcopy(self.grid.are_loads)

**Comment by MarvinLer** [comment]
Yes I'm on it thanks for the details

**Comment by MarvinLer** [comment]
Alright I see what you mean with the problem of 1.
Indeed in the current state it does recompute a loadflow but with a different initial state that after a simulation, hence the modifications of the values of the slack bus.

You are also perfectly right for 2., apply_topo was used to recompute the state (which should be discarded with above) and to recompute are_loads which is modified when the topology changes.

Pushing your proposed changes, thank you for the help!

**Comment by MarvinLer** [comment]
Done in 33617136793d8edb577a32f5f5603c68dd8744eb.
The tests of @BDonnot seem to run, do you confirm this is okay for you @marota ?
