### ISSUE TITLE
function reset

### ISSUE THREAD

**Issue by luvf** [MarvinLer/pypownet#48]
On RunEnv there is a reset method.
this function reset the game :
if game over = "hard"
 -load the next chronic
else
 -load the next timestep

BUT 
It is used in runner.loop() with the meaning to restart the current chronic (to run episodes)
but this will load the next chronic

One time you are using this function to handle game over
One time you are using this function to run episodes

Luca

**Comment by MarvinLer** [comment]
Yes, so the current `reset` function does indeed handle game over, which will either load the next timestep of the current chronic, or the "next" chronic for hard mode. 
The software lacks a proper `reset` function which completely reboot the game environment (to be able to run proper episodes). This function will be implemented within two weeks (and the previous `reset` renamed into something more accurate).

**Comment by MarvinLer** [comment]
So in b93cabff3a2977aaf671783c8606742ec89c92c7, the old ```reset``` function has been renamed into ```process_game_over``` for both RunEnv and Game classes, and a proper ```RunEnv.reset``` function has been implemented that completely restarts the environment. The latter is now called at the beginning of each epoch in the ```loop``` function of the runner.
Also added number of epochs cli argument in 7b686aa0009771106be1051c93a2d0b3a6fc5431.
