### ISSUE TITLE
There is an error in the Pypownet.doc

### ISSUE THREAD

**Issue by roki1031** [MarvinLer/pypownet#50]
Hello

 Thanks for generous contribution to this project. I wonder if you are still updating this project?
 And there is a mistake in the doc of pypownet, which occurs in the subpart of  "Using environment"--"Reading observations". It seems that the description of the observation of "line" are all wrong?

**Comment by MarvinLer** [comment]
Hello,
Thanks for your interest in this library! The project has been stalled for close to two years, but is still somehow maintained. Whitepaper of this software is coming soon, and there should be some performance updates in the next few months on the library itself.

Indeed, description of subpart "line" of observations is completely wrong, will update over the week.

ML

**Comment by roki1031** [comment]
It's wonderful to hear news of continuing maintaining this project.  I think everyone who is committed to applying reinforcement learning to power systems will look forward to the update of this project. And thanks for your quick reply! :)

**Comment by MarvinLer** [comment]
It's fixed
Thanks for your feedback!
