### ISSUE TITLE
Store damaged lines

### ISSUE THREAD

**Issue by bdonon** [MarvinLer/PyPowNet#7]
If a cascading failure results in a line being opened, then store the information that this line is damaged, and make it unavailable for a given time lapse.

**Comment by MarvinLer** [comment]
Added in d945e4c.
The game stores every line artificially disconnected (with cascading failure), and put the remaining timesteps before being reconnectable at 10 by default. When receiving an action that has such an illegal move, the game will change the proposed action to a None action (do nothing move), and increment the reward of the latter by a fixed reward for the illegal move. When such an event occurs and verbose is active (toggle -v with cli argument), the runners will print a warning with some additional info including remaining timesteps. Those are available in the field Observation.timesteps_before_lines_reconnectable (positive value is the time remaining for the associated line, 0 means reconnectable).

Further development will integrate the time before reconnectable as a parameter, and also various timesteps to wait depending on the context of the artificial disconnection by the game (maintenance, or hard-overflow, or random hazard etc). Closing this particular ticket.
